### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by paulmeier** [go-nacelle/pgutil#1]
I'm not sure what I'm doing wrong but I cant get this to connect to a pg docker container. I'm using a connection string `postgres://username:password@localhost:5432`

**Comment by efritz** [comment]
You may need to add `?sslmode=disable` to the end of your connection string in Docker. Let me know if this helps and I'll try to update the connection logic to surface this a bit better.

**Comment by paulmeier** [comment]
That worked thanks.
